// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Hall.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// /登陆类型
type C2S_Login_E_LoginType int32

const (
	// 微信登陆
	C2S_Login_E_LoginType_WeChat C2S_Login_E_LoginType = 0
	// 游客登陆
	C2S_Login_E_LoginType_Guest C2S_Login_E_LoginType = 1
)

var C2S_Login_E_LoginType_name = map[int32]string{
	0: "E_LoginType_WeChat",
	1: "E_LoginType_Guest",
}
var C2S_Login_E_LoginType_value = map[string]int32{
	"E_LoginType_WeChat": 0,
	"E_LoginType_Guest":  1,
}

func (x C2S_Login_E_LoginType) String() string {
	return proto.EnumName(C2S_Login_E_LoginType_name, int32(x))
}
func (C2S_Login_E_LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{0, 0}
}

type S2C_Login_E_ErrReason int32

const (
	// 成功登陆,将下发数据
	S2C_Login_E_Err_SucceeLogin S2C_Login_E_ErrReason = 0
	// 成功创建新账号,读表获取初始数据
	S2C_Login_E_Err_NewAccount S2C_Login_E_ErrReason = 1
	// 登陆信息不匹配,登陆失败
	S2C_Login_E_Err_LoginInfoNotMatch S2C_Login_E_ErrReason = 2
	// 验证通过,允许登陆,但登陆地点异常警告
	S2C_Login_E_Err_LocationWarn S2C_Login_E_ErrReason = 3
)

var S2C_Login_E_ErrReason_name = map[int32]string{
	0: "E_Err_SucceeLogin",
	1: "E_Err_NewAccount",
	2: "E_Err_LoginInfoNotMatch",
	3: "E_Err_LocationWarn",
}
var S2C_Login_E_ErrReason_value = map[string]int32{
	"E_Err_SucceeLogin":       0,
	"E_Err_NewAccount":        1,
	"E_Err_LoginInfoNotMatch": 2,
	"E_Err_LocationWarn":      3,
}

func (x S2C_Login_E_ErrReason) String() string {
	return proto.EnumName(S2C_Login_E_ErrReason_name, int32(x))
}
func (S2C_Login_E_ErrReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{1, 0}
}

type MallProductModel_E_Shoptype int32

const (
	MallProductModel_coin    MallProductModel_E_Shoptype = 0
	MallProductModel_diamond MallProductModel_E_Shoptype = 1
)

var MallProductModel_E_Shoptype_name = map[int32]string{
	0: "coin",
	1: "diamond",
}
var MallProductModel_E_Shoptype_value = map[string]int32{
	"coin":    0,
	"diamond": 1,
}

func (x MallProductModel_E_Shoptype) String() string {
	return proto.EnumName(MallProductModel_E_Shoptype_name, int32(x))
}
func (MallProductModel_E_Shoptype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{9, 0}
}

type QiandaoModel_E_Qiandaotype int32

const (
	QiandaoModel_coin    QiandaoModel_E_Qiandaotype = 0
	QiandaoModel_diamond QiandaoModel_E_Qiandaotype = 1
)

var QiandaoModel_E_Qiandaotype_name = map[int32]string{
	0: "coin",
	1: "diamond",
}
var QiandaoModel_E_Qiandaotype_value = map[string]int32{
	"coin":    0,
	"diamond": 1,
}

func (x QiandaoModel_E_Qiandaotype) String() string {
	return proto.EnumName(QiandaoModel_E_Qiandaotype_name, int32(x))
}
func (QiandaoModel_E_Qiandaotype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{12, 0}
}

// /任务类型 0挑战任务1今日任务2本周任务3成就任务
type TaskModel_E_Tasktype int32

const (
	TaskModel_challenge   TaskModel_E_Tasktype = 0
	TaskModel_day         TaskModel_E_Tasktype = 1
	TaskModel_week        TaskModel_E_Tasktype = 2
	TaskModel_achievement TaskModel_E_Tasktype = 3
)

var TaskModel_E_Tasktype_name = map[int32]string{
	0: "challenge",
	1: "day",
	2: "week",
	3: "achievement",
}
var TaskModel_E_Tasktype_value = map[string]int32{
	"challenge":   0,
	"day":         1,
	"week":        2,
	"achievement": 3,
}

func (x TaskModel_E_Tasktype) String() string {
	return proto.EnumName(TaskModel_E_Tasktype_name, int32(x))
}
func (TaskModel_E_Tasktype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{15, 0}
}

// /邮件类型0正常邮件1系统邮件
type MailModel_E_Mailtype int32

const (
	MailModel_normalmail MailModel_E_Mailtype = 0
	MailModel_systemmial MailModel_E_Mailtype = 1
)

var MailModel_E_Mailtype_name = map[int32]string{
	0: "normalmail",
	1: "systemmial",
}
var MailModel_E_Mailtype_value = map[string]int32{
	"normalmail": 0,
	"systemmial": 1,
}

func (x MailModel_E_Mailtype) String() string {
	return proto.EnumName(MailModel_E_Mailtype_name, int32(x))
}
func (MailModel_E_Mailtype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{18, 0}
}

// /金币0，钻石1，物品2
type MailModel_E_Awardtype int32

const (
	MailModel_coin    MailModel_E_Awardtype = 0
	MailModel_diamond MailModel_E_Awardtype = 1
	MailModel_goods   MailModel_E_Awardtype = 2
)

var MailModel_E_Awardtype_name = map[int32]string{
	0: "coin",
	1: "diamond",
	2: "goods",
}
var MailModel_E_Awardtype_value = map[string]int32{
	"coin":    0,
	"diamond": 1,
	"goods":   2,
}

func (x MailModel_E_Awardtype) String() string {
	return proto.EnumName(MailModel_E_Awardtype_name, int32(x))
}
func (MailModel_E_Awardtype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{18, 1}
}

// /登陆请求
// @msg
type C2S_Login struct {
	// /微信登陆时是微信uid,游客登陆时是手机唯一标识
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// /用户昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// /用户头像url
	Head string `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	// /性别
	Sex string `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	// 微信登陆传openid，游客登陆传空
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// /地理位置
	Location             string                `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Logintype            C2S_Login_E_LoginType `protobuf:"varint,7,opt,name=logintype,proto3,enum=msg.C2S_Login_E_LoginType" json:"logintype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *C2S_Login) Reset()         { *m = C2S_Login{} }
func (m *C2S_Login) String() string { return proto.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()    {}
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{0}
}
func (m *C2S_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Login.Unmarshal(m, b)
}
func (m *C2S_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Login.Marshal(b, m, deterministic)
}
func (dst *C2S_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Login.Merge(dst, src)
}
func (m *C2S_Login) XXX_Size() int {
	return xxx_messageInfo_C2S_Login.Size(m)
}
func (m *C2S_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Login.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Login proto.InternalMessageInfo

func (m *C2S_Login) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *C2S_Login) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *C2S_Login) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *C2S_Login) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *C2S_Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *C2S_Login) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *C2S_Login) GetLogintype() C2S_Login_E_LoginType {
	if m != nil {
		return m.Logintype
	}
	return C2S_Login_E_LoginType_WeChat
}

// /登陆回复
// @msg
type S2C_Login struct {
	Reason               S2C_Login_E_ErrReason `protobuf:"varint,1,opt,name=reason,proto3,enum=msg.S2C_Login_E_ErrReason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2C_Login) Reset()         { *m = S2C_Login{} }
func (m *S2C_Login) String() string { return proto.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()    {}
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{1}
}
func (m *S2C_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Login.Unmarshal(m, b)
}
func (m *S2C_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Login.Marshal(b, m, deterministic)
}
func (dst *S2C_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Login.Merge(dst, src)
}
func (m *S2C_Login) XXX_Size() int {
	return xxx_messageInfo_S2C_Login.Size(m)
}
func (m *S2C_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Login.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Login proto.InternalMessageInfo

func (m *S2C_Login) GetReason() S2C_Login_E_ErrReason {
	if m != nil {
		return m.Reason
	}
	return S2C_Login_E_Err_SucceeLogin
}

// /玩家公开信息
// @msg
type Player struct {
	// /玩家id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// /昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// /头像
	Head string `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	// /金币
	Money int32 `protobuf:"varint,4,opt,name=money,proto3" json:"money,omitempty"`
	// /等级
	Grade int32 `protobuf:"varint,5,opt,name=grade,proto3" json:"grade,omitempty"`
	// /积分
	Interial             int64    `protobuf:"varint,6,opt,name=interial,proto3" json:"interial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{2}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Player) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *Player) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *Player) GetGrade() int32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

func (m *Player) GetInterial() int64 {
	if m != nil {
		return m.Interial
	}
	return 0
}

// /服务端大厅广播
// @msg
type S2C_HallBroadCast struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_HallBroadCast) Reset()         { *m = S2C_HallBroadCast{} }
func (m *S2C_HallBroadCast) String() string { return proto.CompactTextString(m) }
func (*S2C_HallBroadCast) ProtoMessage()    {}
func (*S2C_HallBroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{3}
}
func (m *S2C_HallBroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_HallBroadCast.Unmarshal(m, b)
}
func (m *S2C_HallBroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_HallBroadCast.Marshal(b, m, deterministic)
}
func (dst *S2C_HallBroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_HallBroadCast.Merge(dst, src)
}
func (m *S2C_HallBroadCast) XXX_Size() int {
	return xxx_messageInfo_S2C_HallBroadCast.Size(m)
}
func (m *S2C_HallBroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_HallBroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_HallBroadCast proto.InternalMessageInfo

// /客户端向服务器发送用户信息请求
// @msg
type C2S_Userinfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_Userinfo) Reset()         { *m = C2S_Userinfo{} }
func (m *C2S_Userinfo) String() string { return proto.CompactTextString(m) }
func (*C2S_Userinfo) ProtoMessage()    {}
func (*C2S_Userinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{4}
}
func (m *C2S_Userinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Userinfo.Unmarshal(m, b)
}
func (m *C2S_Userinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Userinfo.Marshal(b, m, deterministic)
}
func (dst *C2S_Userinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Userinfo.Merge(dst, src)
}
func (m *C2S_Userinfo) XXX_Size() int {
	return xxx_messageInfo_C2S_Userinfo.Size(m)
}
func (m *C2S_Userinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Userinfo.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Userinfo proto.InternalMessageInfo

// /服务端个人信息返回
// @msg
type S2C_Userinfo struct {
	Userinfo             *UserModel `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2C_Userinfo) Reset()         { *m = S2C_Userinfo{} }
func (m *S2C_Userinfo) String() string { return proto.CompactTextString(m) }
func (*S2C_Userinfo) ProtoMessage()    {}
func (*S2C_Userinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{5}
}
func (m *S2C_Userinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Userinfo.Unmarshal(m, b)
}
func (m *S2C_Userinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Userinfo.Marshal(b, m, deterministic)
}
func (dst *S2C_Userinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Userinfo.Merge(dst, src)
}
func (m *S2C_Userinfo) XXX_Size() int {
	return xxx_messageInfo_S2C_Userinfo.Size(m)
}
func (m *S2C_Userinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Userinfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Userinfo proto.InternalMessageInfo

func (m *S2C_Userinfo) GetUserinfo() *UserModel {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

// @msg
type UserModel struct {
	// /公共信息
	Playerinfo *Player `protobuf:"bytes,1,opt,name=playerinfo,proto3" json:"playerinfo,omitempty"`
	// /局数
	Jushu int64 `protobuf:"varint,2,opt,name=jushu,proto3" json:"jushu,omitempty"`
	// /入场率
	Rujurate int32 `protobuf:"varint,3,opt,name=rujurate,proto3" json:"rujurate,omitempty"`
	// /胜率
	Shenglurate int32 `protobuf:"varint,4,opt,name=shenglurate,proto3" json:"shenglurate,omitempty"`
	// /摊派率
	Tanpairate int32 `protobuf:"varint,5,opt,name=tanpairate,proto3" json:"tanpairate,omitempty"`
	// /最大牌型idlist
	Ids                  []string `protobuf:"bytes,6,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserModel) Reset()         { *m = UserModel{} }
func (m *UserModel) String() string { return proto.CompactTextString(m) }
func (*UserModel) ProtoMessage()    {}
func (*UserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{6}
}
func (m *UserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserModel.Unmarshal(m, b)
}
func (m *UserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserModel.Marshal(b, m, deterministic)
}
func (dst *UserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserModel.Merge(dst, src)
}
func (m *UserModel) XXX_Size() int {
	return xxx_messageInfo_UserModel.Size(m)
}
func (m *UserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserModel proto.InternalMessageInfo

func (m *UserModel) GetPlayerinfo() *Player {
	if m != nil {
		return m.Playerinfo
	}
	return nil
}

func (m *UserModel) GetJushu() int64 {
	if m != nil {
		return m.Jushu
	}
	return 0
}

func (m *UserModel) GetRujurate() int32 {
	if m != nil {
		return m.Rujurate
	}
	return 0
}

func (m *UserModel) GetShenglurate() int32 {
	if m != nil {
		return m.Shenglurate
	}
	return 0
}

func (m *UserModel) GetTanpairate() int32 {
	if m != nil {
		return m.Tanpairate
	}
	return 0
}

func (m *UserModel) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

// /客户端向服务端发送商品列表请求
// @msg
type C2S_MallProduct struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_MallProduct) Reset()         { *m = C2S_MallProduct{} }
func (m *C2S_MallProduct) String() string { return proto.CompactTextString(m) }
func (*C2S_MallProduct) ProtoMessage()    {}
func (*C2S_MallProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{7}
}
func (m *C2S_MallProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_MallProduct.Unmarshal(m, b)
}
func (m *C2S_MallProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_MallProduct.Marshal(b, m, deterministic)
}
func (dst *C2S_MallProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_MallProduct.Merge(dst, src)
}
func (m *C2S_MallProduct) XXX_Size() int {
	return xxx_messageInfo_C2S_MallProduct.Size(m)
}
func (m *C2S_MallProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_MallProduct.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_MallProduct proto.InternalMessageInfo

// /服务端向客户端发送商品列表
// @msg
type S2C_MallProduct struct {
	Products             []*MallProductModel `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *S2C_MallProduct) Reset()         { *m = S2C_MallProduct{} }
func (m *S2C_MallProduct) String() string { return proto.CompactTextString(m) }
func (*S2C_MallProduct) ProtoMessage()    {}
func (*S2C_MallProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{8}
}
func (m *S2C_MallProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_MallProduct.Unmarshal(m, b)
}
func (m *S2C_MallProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_MallProduct.Marshal(b, m, deterministic)
}
func (dst *S2C_MallProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_MallProduct.Merge(dst, src)
}
func (m *S2C_MallProduct) XXX_Size() int {
	return xxx_messageInfo_S2C_MallProduct.Size(m)
}
func (m *S2C_MallProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_MallProduct.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_MallProduct proto.InternalMessageInfo

func (m *S2C_MallProduct) GetProducts() []*MallProductModel {
	if m != nil {
		return m.Products
	}
	return nil
}

// @msg
type MallProductModel struct {
	// /商品id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// /商品名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// /商品图片
	Image    string                      `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Shoptype MallProductModel_E_Shoptype `protobuf:"varint,4,opt,name=shoptype,proto3,enum=msg.MallProductModel_E_Shoptype" json:"shoptype,omitempty"`
	// /价格
	Price int32 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	// /道具数量
	Itemcount            int32    `protobuf:"varint,6,opt,name=itemcount,proto3" json:"itemcount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MallProductModel) Reset()         { *m = MallProductModel{} }
func (m *MallProductModel) String() string { return proto.CompactTextString(m) }
func (*MallProductModel) ProtoMessage()    {}
func (*MallProductModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{9}
}
func (m *MallProductModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MallProductModel.Unmarshal(m, b)
}
func (m *MallProductModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MallProductModel.Marshal(b, m, deterministic)
}
func (dst *MallProductModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MallProductModel.Merge(dst, src)
}
func (m *MallProductModel) XXX_Size() int {
	return xxx_messageInfo_MallProductModel.Size(m)
}
func (m *MallProductModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MallProductModel.DiscardUnknown(m)
}

var xxx_messageInfo_MallProductModel proto.InternalMessageInfo

func (m *MallProductModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MallProductModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MallProductModel) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MallProductModel) GetShoptype() MallProductModel_E_Shoptype {
	if m != nil {
		return m.Shoptype
	}
	return MallProductModel_coin
}

func (m *MallProductModel) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MallProductModel) GetItemcount() int32 {
	if m != nil {
		return m.Itemcount
	}
	return 0
}

// /客户端向服务端发送签到请求
// @msg
type C2S_Qiandao struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_Qiandao) Reset()         { *m = C2S_Qiandao{} }
func (m *C2S_Qiandao) String() string { return proto.CompactTextString(m) }
func (*C2S_Qiandao) ProtoMessage()    {}
func (*C2S_Qiandao) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{10}
}
func (m *C2S_Qiandao) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Qiandao.Unmarshal(m, b)
}
func (m *C2S_Qiandao) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Qiandao.Marshal(b, m, deterministic)
}
func (dst *C2S_Qiandao) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Qiandao.Merge(dst, src)
}
func (m *C2S_Qiandao) XXX_Size() int {
	return xxx_messageInfo_C2S_Qiandao.Size(m)
}
func (m *C2S_Qiandao) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Qiandao.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Qiandao proto.InternalMessageInfo

// /服务器向客户端发送签到列表
// @msg
type S2C_QiandaoBrocast struct {
	Products             []*QiandaoModel `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *S2C_QiandaoBrocast) Reset()         { *m = S2C_QiandaoBrocast{} }
func (m *S2C_QiandaoBrocast) String() string { return proto.CompactTextString(m) }
func (*S2C_QiandaoBrocast) ProtoMessage()    {}
func (*S2C_QiandaoBrocast) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{11}
}
func (m *S2C_QiandaoBrocast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_QiandaoBrocast.Unmarshal(m, b)
}
func (m *S2C_QiandaoBrocast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_QiandaoBrocast.Marshal(b, m, deterministic)
}
func (dst *S2C_QiandaoBrocast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_QiandaoBrocast.Merge(dst, src)
}
func (m *S2C_QiandaoBrocast) XXX_Size() int {
	return xxx_messageInfo_S2C_QiandaoBrocast.Size(m)
}
func (m *S2C_QiandaoBrocast) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_QiandaoBrocast.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_QiandaoBrocast proto.InternalMessageInfo

func (m *S2C_QiandaoBrocast) GetProducts() []*QiandaoModel {
	if m != nil {
		return m.Products
	}
	return nil
}

// @msg
type QiandaoModel struct {
	// /签到id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// /签到名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// /签到图片
	Image       string                     `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Qiandaotype QiandaoModel_E_Qiandaotype `protobuf:"varint,4,opt,name=qiandaotype,proto3,enum=msg.QiandaoModel_E_Qiandaotype" json:"qiandaotype,omitempty"`
	// /奖励数量
	Awardnum int32 `protobuf:"varint,5,opt,name=awardnum,proto3" json:"awardnum,omitempty"`
	// /领取状态
	Status               bool     `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QiandaoModel) Reset()         { *m = QiandaoModel{} }
func (m *QiandaoModel) String() string { return proto.CompactTextString(m) }
func (*QiandaoModel) ProtoMessage()    {}
func (*QiandaoModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{12}
}
func (m *QiandaoModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QiandaoModel.Unmarshal(m, b)
}
func (m *QiandaoModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QiandaoModel.Marshal(b, m, deterministic)
}
func (dst *QiandaoModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QiandaoModel.Merge(dst, src)
}
func (m *QiandaoModel) XXX_Size() int {
	return xxx_messageInfo_QiandaoModel.Size(m)
}
func (m *QiandaoModel) XXX_DiscardUnknown() {
	xxx_messageInfo_QiandaoModel.DiscardUnknown(m)
}

var xxx_messageInfo_QiandaoModel proto.InternalMessageInfo

func (m *QiandaoModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QiandaoModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QiandaoModel) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *QiandaoModel) GetQiandaotype() QiandaoModel_E_Qiandaotype {
	if m != nil {
		return m.Qiandaotype
	}
	return QiandaoModel_coin
}

func (m *QiandaoModel) GetAwardnum() int32 {
	if m != nil {
		return m.Awardnum
	}
	return 0
}

func (m *QiandaoModel) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// /客户端向服务器发送任务信息请求
// @msg
type C2S_TaskList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_TaskList) Reset()         { *m = C2S_TaskList{} }
func (m *C2S_TaskList) String() string { return proto.CompactTextString(m) }
func (*C2S_TaskList) ProtoMessage()    {}
func (*C2S_TaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{13}
}
func (m *C2S_TaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_TaskList.Unmarshal(m, b)
}
func (m *C2S_TaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_TaskList.Marshal(b, m, deterministic)
}
func (dst *C2S_TaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_TaskList.Merge(dst, src)
}
func (m *C2S_TaskList) XXX_Size() int {
	return xxx_messageInfo_C2S_TaskList.Size(m)
}
func (m *C2S_TaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_TaskList.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_TaskList proto.InternalMessageInfo

// @msg
type S2C_TaskList struct {
	// /任务列表
	Products             []*TaskModel `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2C_TaskList) Reset()         { *m = S2C_TaskList{} }
func (m *S2C_TaskList) String() string { return proto.CompactTextString(m) }
func (*S2C_TaskList) ProtoMessage()    {}
func (*S2C_TaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{14}
}
func (m *S2C_TaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_TaskList.Unmarshal(m, b)
}
func (m *S2C_TaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_TaskList.Marshal(b, m, deterministic)
}
func (dst *S2C_TaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_TaskList.Merge(dst, src)
}
func (m *S2C_TaskList) XXX_Size() int {
	return xxx_messageInfo_S2C_TaskList.Size(m)
}
func (m *S2C_TaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_TaskList.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_TaskList proto.InternalMessageInfo

func (m *S2C_TaskList) GetProducts() []*TaskModel {
	if m != nil {
		return m.Products
	}
	return nil
}

// @msg
type TaskModel struct {
	// /任务id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// /任务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// /任务图片，直接传图片名字
	Image    string               `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Tasktype TaskModel_E_Tasktype `protobuf:"varint,4,opt,name=tasktype,proto3,enum=msg.TaskModel_E_Tasktype" json:"tasktype,omitempty"`
	// /任务描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// /奖励数量
	Awardnum int32 `protobuf:"varint,7,opt,name=awardnum,proto3" json:"awardnum,omitempty"`
	// /任务完成次数
	Finish int32 `protobuf:"varint,8,opt,name=finish,proto3" json:"finish,omitempty"`
	// /任务总次数
	Zong                 int32    `protobuf:"varint,9,opt,name=zong,proto3" json:"zong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskModel) Reset()         { *m = TaskModel{} }
func (m *TaskModel) String() string { return proto.CompactTextString(m) }
func (*TaskModel) ProtoMessage()    {}
func (*TaskModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{15}
}
func (m *TaskModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskModel.Unmarshal(m, b)
}
func (m *TaskModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskModel.Marshal(b, m, deterministic)
}
func (dst *TaskModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskModel.Merge(dst, src)
}
func (m *TaskModel) XXX_Size() int {
	return xxx_messageInfo_TaskModel.Size(m)
}
func (m *TaskModel) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskModel.DiscardUnknown(m)
}

var xxx_messageInfo_TaskModel proto.InternalMessageInfo

func (m *TaskModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskModel) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *TaskModel) GetTasktype() TaskModel_E_Tasktype {
	if m != nil {
		return m.Tasktype
	}
	return TaskModel_challenge
}

func (m *TaskModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TaskModel) GetAwardnum() int32 {
	if m != nil {
		return m.Awardnum
	}
	return 0
}

func (m *TaskModel) GetFinish() int32 {
	if m != nil {
		return m.Finish
	}
	return 0
}

func (m *TaskModel) GetZong() int32 {
	if m != nil {
		return m.Zong
	}
	return 0
}

// @msg
type C2S_MailList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_MailList) Reset()         { *m = C2S_MailList{} }
func (m *C2S_MailList) String() string { return proto.CompactTextString(m) }
func (*C2S_MailList) ProtoMessage()    {}
func (*C2S_MailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{16}
}
func (m *C2S_MailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_MailList.Unmarshal(m, b)
}
func (m *C2S_MailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_MailList.Marshal(b, m, deterministic)
}
func (dst *C2S_MailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_MailList.Merge(dst, src)
}
func (m *C2S_MailList) XXX_Size() int {
	return xxx_messageInfo_C2S_MailList.Size(m)
}
func (m *C2S_MailList) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_MailList.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_MailList proto.InternalMessageInfo

// @msg
type S2C_MailList struct {
	// /邮件列表
	Products             []*MailModel `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2C_MailList) Reset()         { *m = S2C_MailList{} }
func (m *S2C_MailList) String() string { return proto.CompactTextString(m) }
func (*S2C_MailList) ProtoMessage()    {}
func (*S2C_MailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{17}
}
func (m *S2C_MailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_MailList.Unmarshal(m, b)
}
func (m *S2C_MailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_MailList.Marshal(b, m, deterministic)
}
func (dst *S2C_MailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_MailList.Merge(dst, src)
}
func (m *S2C_MailList) XXX_Size() int {
	return xxx_messageInfo_S2C_MailList.Size(m)
}
func (m *S2C_MailList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_MailList.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_MailList proto.InternalMessageInfo

func (m *S2C_MailList) GetProducts() []*MailModel {
	if m != nil {
		return m.Products
	}
	return nil
}

// @msg
type MailModel struct {
	// /邮件id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// /邮件图片
	Image     string                `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Mailtype  MailModel_E_Mailtype  `protobuf:"varint,3,opt,name=mailtype,proto3,enum=msg.MailModel_E_Mailtype" json:"mailtype,omitempty"`
	Awardtype MailModel_E_Awardtype `protobuf:"varint,4,opt,name=awardtype,proto3,enum=msg.MailModel_E_Awardtype" json:"awardtype,omitempty"`
	// /邮件描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// /邮件时间
	Time                 string   `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailModel) Reset()         { *m = MailModel{} }
func (m *MailModel) String() string { return proto.CompactTextString(m) }
func (*MailModel) ProtoMessage()    {}
func (*MailModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_Hall_4c16fa7bdb4b61b7, []int{18}
}
func (m *MailModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailModel.Unmarshal(m, b)
}
func (m *MailModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailModel.Marshal(b, m, deterministic)
}
func (dst *MailModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailModel.Merge(dst, src)
}
func (m *MailModel) XXX_Size() int {
	return xxx_messageInfo_MailModel.Size(m)
}
func (m *MailModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MailModel.DiscardUnknown(m)
}

var xxx_messageInfo_MailModel proto.InternalMessageInfo

func (m *MailModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MailModel) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MailModel) GetMailtype() MailModel_E_Mailtype {
	if m != nil {
		return m.Mailtype
	}
	return MailModel_normalmail
}

func (m *MailModel) GetAwardtype() MailModel_E_Awardtype {
	if m != nil {
		return m.Awardtype
	}
	return MailModel_coin
}

func (m *MailModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MailModel) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*C2S_Login)(nil), "msg.C2S_Login")
	proto.RegisterType((*S2C_Login)(nil), "msg.S2C_Login")
	proto.RegisterType((*Player)(nil), "msg.Player")
	proto.RegisterType((*S2C_HallBroadCast)(nil), "msg.S2C_HallBroadCast")
	proto.RegisterType((*C2S_Userinfo)(nil), "msg.C2S_Userinfo")
	proto.RegisterType((*S2C_Userinfo)(nil), "msg.S2C_Userinfo")
	proto.RegisterType((*UserModel)(nil), "msg.UserModel")
	proto.RegisterType((*C2S_MallProduct)(nil), "msg.C2S_MallProduct")
	proto.RegisterType((*S2C_MallProduct)(nil), "msg.S2C_MallProduct")
	proto.RegisterType((*MallProductModel)(nil), "msg.MallProductModel")
	proto.RegisterType((*C2S_Qiandao)(nil), "msg.C2S_Qiandao")
	proto.RegisterType((*S2C_QiandaoBrocast)(nil), "msg.S2C_QiandaoBrocast")
	proto.RegisterType((*QiandaoModel)(nil), "msg.QiandaoModel")
	proto.RegisterType((*C2S_TaskList)(nil), "msg.C2S_TaskList")
	proto.RegisterType((*S2C_TaskList)(nil), "msg.S2C_TaskList")
	proto.RegisterType((*TaskModel)(nil), "msg.TaskModel")
	proto.RegisterType((*C2S_MailList)(nil), "msg.C2S_MailList")
	proto.RegisterType((*S2C_MailList)(nil), "msg.S2C_MailList")
	proto.RegisterType((*MailModel)(nil), "msg.MailModel")
	proto.RegisterEnum("msg.C2S_Login_E_LoginType", C2S_Login_E_LoginType_name, C2S_Login_E_LoginType_value)
	proto.RegisterEnum("msg.S2C_Login_E_ErrReason", S2C_Login_E_ErrReason_name, S2C_Login_E_ErrReason_value)
	proto.RegisterEnum("msg.MallProductModel_E_Shoptype", MallProductModel_E_Shoptype_name, MallProductModel_E_Shoptype_value)
	proto.RegisterEnum("msg.QiandaoModel_E_Qiandaotype", QiandaoModel_E_Qiandaotype_name, QiandaoModel_E_Qiandaotype_value)
	proto.RegisterEnum("msg.TaskModel_E_Tasktype", TaskModel_E_Tasktype_name, TaskModel_E_Tasktype_value)
	proto.RegisterEnum("msg.MailModel_E_Mailtype", MailModel_E_Mailtype_name, MailModel_E_Mailtype_value)
	proto.RegisterEnum("msg.MailModel_E_Awardtype", MailModel_E_Awardtype_name, MailModel_E_Awardtype_value)
}

func init() { proto.RegisterFile("Hall.proto", fileDescriptor_Hall_4c16fa7bdb4b61b7) }

var fileDescriptor_Hall_4c16fa7bdb4b61b7 = []byte{
	// 993 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdd, 0x6e, 0xe4, 0x34,
	0x14, 0xc7, 0x9b, 0x64, 0x66, 0x3a, 0x39, 0xd3, 0x8f, 0xd4, 0xec, 0x2e, 0xa1, 0x20, 0x18, 0x05,
	0x09, 0x55, 0x7c, 0x0c, 0x62, 0x10, 0x12, 0x42, 0x2b, 0xa1, 0x6e, 0x19, 0x01, 0xd2, 0x76, 0xb5,
	0xa4, 0x8b, 0xf6, 0xb2, 0x32, 0x89, 0x3b, 0xe3, 0x6d, 0x62, 0x07, 0xdb, 0xa1, 0x3b, 0xbc, 0x04,
	0xbc, 0x05, 0xb7, 0xdc, 0x71, 0xc7, 0xcb, 0x70, 0xc1, 0x6b, 0x20, 0x1f, 0x27, 0x69, 0x3a, 0xa5,
	0x12, 0x62, 0xaf, 0xc6, 0xff, 0x73, 0x8e, 0x4f, 0x8e, 0x7f, 0x3e, 0x47, 0x1e, 0x80, 0x6f, 0x68,
	0x51, 0xcc, 0x2a, 0x25, 0x8d, 0x24, 0x41, 0xa9, 0x97, 0xc9, 0x2f, 0x3e, 0x84, 0x27, 0xf3, 0xb3,
	0xf3, 0xc7, 0x72, 0xc9, 0x05, 0x89, 0x20, 0xa8, 0x79, 0x1e, 0x7b, 0x53, 0xef, 0x28, 0x4c, 0xed,
	0x92, 0x1c, 0xc2, 0x58, 0xf0, 0xec, 0x52, 0xd0, 0x92, 0xc5, 0x3e, 0x9a, 0x3b, 0x4d, 0x08, 0x0c,
	0x56, 0x8c, 0xe6, 0x71, 0x80, 0x76, 0x5c, 0xdb, 0x0c, 0x9a, 0xbd, 0x8c, 0x07, 0x2e, 0x83, 0x66,
	0x2f, 0x6d, 0x86, 0x8a, 0x6a, 0x7d, 0x25, 0x55, 0x1e, 0x0f, 0x5d, 0x86, 0x56, 0x5b, 0x5f, 0x21,
	0x33, 0x6a, 0xb8, 0x14, 0xf1, 0xc8, 0xf9, 0x5a, 0x4d, 0x3e, 0x87, 0xb0, 0xb0, 0x45, 0x99, 0x75,
	0xc5, 0xe2, 0xed, 0xa9, 0x77, 0xb4, 0x37, 0x3f, 0x9c, 0x95, 0x7a, 0x39, 0xeb, 0xca, 0x9d, 0x2d,
	0xdc, 0xef, 0xb3, 0x75, 0xc5, 0xd2, 0xeb, 0xe0, 0xe4, 0x21, 0x4c, 0x7a, 0x1e, 0xf2, 0x00, 0x48,
	0x4f, 0x9e, 0x3f, 0x67, 0x27, 0x2b, 0x6a, 0xa2, 0x2d, 0x72, 0x1f, 0x0e, 0xfa, 0xf6, 0xaf, 0x6b,
	0xa6, 0x4d, 0xe4, 0x25, 0xbf, 0x7b, 0x10, 0x9e, 0xcd, 0x4f, 0x1a, 0x22, 0x73, 0x18, 0x29, 0x46,
	0xb5, 0x14, 0x08, 0xa5, 0x2d, 0xa1, 0xf3, 0xcf, 0x16, 0xe7, 0x0b, 0xa5, 0x52, 0x8c, 0x48, 0x9b,
	0xc8, 0x44, 0xda, 0xef, 0x77, 0x66, 0xf7, 0x9d, 0x85, 0x52, 0xe7, 0x67, 0x75, 0x96, 0x31, 0x86,
	0xfb, 0xa2, 0x2d, 0x72, 0x0f, 0x22, 0x67, 0x7e, 0xc2, 0xae, 0x8e, 0xb3, 0x4c, 0xd6, 0xc2, 0x44,
	0x1e, 0x79, 0x13, 0x5e, 0x77, 0x56, 0x0c, 0xfb, 0x56, 0x5c, 0xc8, 0x27, 0xd2, 0x9c, 0x52, 0x93,
	0xad, 0x22, 0xdf, 0x9d, 0xc4, 0x39, 0x1d, 0xa4, 0xe7, 0x54, 0x89, 0x28, 0x48, 0x7e, 0xf5, 0x60,
	0xf4, 0xb4, 0xa0, 0x6b, 0xa6, 0xc8, 0x1e, 0xf8, 0xcd, 0x05, 0x0e, 0x53, 0xff, 0x7f, 0xdc, 0xdf,
	0x3d, 0x18, 0x96, 0x52, 0xb0, 0x35, 0xde, 0xe0, 0x30, 0x75, 0xc2, 0x5a, 0x97, 0x8a, 0xe6, 0x0c,
	0x2f, 0x70, 0x98, 0x3a, 0x61, 0x73, 0x73, 0x61, 0x98, 0xe2, 0xb4, 0xc0, 0xdb, 0x0b, 0xd2, 0x4e,
	0x27, 0xaf, 0xc1, 0x81, 0x85, 0x64, 0xdb, 0xed, 0x91, 0x92, 0x34, 0x3f, 0xa1, 0xda, 0x24, 0x7b,
	0xb0, 0x63, 0x2f, 0xef, 0x7b, 0xcd, 0x14, 0x17, 0x17, 0x32, 0xf9, 0x02, 0x76, 0x6c, 0x50, 0xab,
	0xc9, 0xfb, 0x30, 0xae, 0x9b, 0x35, 0x1e, 0x61, 0x32, 0xdf, 0x43, 0xdc, 0x36, 0xe0, 0x54, 0xe6,
	0xac, 0x48, 0x3b, 0x7f, 0xf2, 0xa7, 0x07, 0x61, 0x67, 0x27, 0x1f, 0x00, 0x54, 0x08, 0xa0, 0xb7,
	0x77, 0x82, 0x7b, 0x1d, 0x97, 0xb4, 0xe7, 0xb6, 0xa7, 0x79, 0x51, 0xeb, 0x55, 0x8d, 0x40, 0x82,
	0xd4, 0x09, 0x7b, 0x1a, 0x55, 0xbf, 0xa8, 0x15, 0x35, 0x0c, 0x89, 0x0c, 0xd3, 0x4e, 0x93, 0x29,
	0x4c, 0xf4, 0x8a, 0x89, 0x65, 0xe1, 0xdc, 0x8e, 0x4d, 0xdf, 0x44, 0xde, 0x06, 0x30, 0x54, 0x54,
	0x94, 0x63, 0x80, 0xc3, 0xd4, 0xb3, 0xd8, 0xb9, 0xe0, 0xb9, 0x8e, 0x47, 0xd3, 0xc0, 0xce, 0x05,
	0xcf, 0x75, 0x72, 0x00, 0xfb, 0x16, 0xc6, 0x29, 0x2d, 0x8a, 0xa7, 0x4a, 0xe6, 0x75, 0x66, 0x92,
	0xaf, 0x60, 0xdf, 0xf2, 0xe8, 0x99, 0xc8, 0x27, 0x30, 0xae, 0xdc, 0x52, 0xc7, 0xde, 0x34, 0x38,
	0x9a, 0xcc, 0xef, 0xe3, 0xb1, 0x7a, 0x31, 0x0d, 0x99, 0x36, 0x2c, 0xf9, 0xcb, 0x83, 0x68, 0xd3,
	0xdd, 0xeb, 0x8b, 0x10, 0xfb, 0x82, 0xc0, 0xa0, 0xd7, 0x13, 0xb8, 0xb6, 0x5c, 0x78, 0x49, 0x97,
	0xac, 0x69, 0x08, 0x27, 0xc8, 0x43, 0x18, 0xeb, 0x95, 0xac, 0x70, 0x0c, 0x07, 0x38, 0x03, 0xd3,
	0x7f, 0xad, 0x60, 0xb6, 0x38, 0x3f, 0x6b, 0xe2, 0xd2, 0x6e, 0x87, 0xcd, 0x59, 0x29, 0x9e, 0x75,
	0x9d, 0x83, 0x82, 0xbc, 0x05, 0x21, 0x37, 0xac, 0xc4, 0xa6, 0xc7, 0xd6, 0x19, 0xa6, 0xd7, 0x86,
	0xe4, 0x5d, 0x80, 0xeb, 0x5c, 0x64, 0x0c, 0x83, 0x4c, 0xe2, 0xc4, 0x4c, 0x60, 0x3b, 0xe7, 0xb4,
	0x94, 0x22, 0x8f, 0xbc, 0x64, 0x17, 0x26, 0x16, 0xdf, 0x77, 0x9c, 0x8a, 0x9c, 0xca, 0xe4, 0x04,
	0x88, 0x45, 0xd7, 0xc8, 0x47, 0x4a, 0x66, 0x54, 0x1b, 0xf2, 0xd1, 0x2d, 0x7a, 0x07, 0x58, 0x7b,
	0x13, 0xb6, 0x49, 0xee, 0x6f, 0x0f, 0x76, 0xfa, 0xae, 0x57, 0xa0, 0x76, 0x0c, 0x93, 0x1f, 0x5d,
	0xa6, 0x1e, 0xb8, 0x77, 0x6e, 0x7d, 0x7c, 0xb6, 0x68, 0x4b, 0x46, 0x6e, 0xfd, 0x3d, 0xb6, 0x21,
	0xe9, 0x15, 0x55, 0xb9, 0xa8, 0xcb, 0x86, 0x5e, 0xa7, 0xc9, 0x03, 0x18, 0x69, 0x43, 0x4d, 0xad,
	0x91, 0xde, 0x38, 0x6d, 0x54, 0xf2, 0x1e, 0xec, 0xde, 0xc8, 0x78, 0x17, 0xbd, 0x66, 0x12, 0x9f,
	0x51, 0x7d, 0xf9, 0x98, 0x6b, 0xd3, 0x4e, 0x62, 0xab, 0xed, 0x24, 0x6e, 0x80, 0x73, 0x93, 0x68,
	0x03, 0x36, 0xa9, 0xfd, 0xe6, 0x43, 0xd8, 0xd9, 0x5f, 0x01, 0xd9, 0x67, 0x30, 0x36, 0x54, 0x5f,
	0xf6, 0x78, 0xbd, 0x71, 0xf3, 0x9b, 0xb3, 0x05, 0x16, 0xe8, 0x3a, 0xac, 0x0d, 0xb5, 0xb3, 0x99,
	0x33, 0x9d, 0x29, 0x5e, 0xe1, 0x33, 0xe2, 0x9e, 0x98, 0xbe, 0xe9, 0x06, 0xc8, 0xed, 0xdb, 0x20,
	0x2f, 0xb8, 0xe0, 0x7a, 0x15, 0x8f, 0xd1, 0xd3, 0x28, 0x5b, 0xf6, 0xcf, 0x52, 0x2c, 0xe3, 0x10,
	0xad, 0xb8, 0x4e, 0xbe, 0xb4, 0x7d, 0xd9, 0x56, 0x40, 0x76, 0x21, 0xcc, 0x56, 0xb4, 0x28, 0x98,
	0x58, 0xb2, 0x68, 0x8b, 0x6c, 0x43, 0x90, 0xd3, 0x75, 0xe4, 0x59, 0xe2, 0x57, 0x8c, 0x5d, 0x46,
	0x3e, 0xd9, 0x87, 0x09, 0xcd, 0x56, 0x9c, 0xfd, 0xc4, 0x4a, 0x26, 0x4c, 0x14, 0xb4, 0xd4, 0x4f,
	0x29, 0x2f, 0xfa, 0xd4, 0x5b, 0x7d, 0x27, 0x75, 0x1b, 0xb0, 0x49, 0xfd, 0x0f, 0x1f, 0xc2, 0xce,
	0x7e, 0x8b, 0x7a, 0x47, 0xd8, 0xdf, 0x20, 0x5c, 0x52, 0x5e, 0x20, 0xe1, 0xa0, 0x47, 0xb8, 0xcb,
	0x33, 0x5b, 0x60, 0x31, 0x8e, 0x70, 0x1b, 0x6a, 0x5f, 0x62, 0xe4, 0xd5, 0xbb, 0x99, 0xc3, 0x5b,
	0xfb, 0x8e, 0xdb, 0x88, 0xf4, 0x3a, 0xf8, 0x3f, 0xdc, 0x0d, 0x81, 0x81, 0xe1, 0x25, 0x6b, 0x5e,
	0x7f, 0x5c, 0x27, 0x1f, 0x5a, 0xce, 0x6d, 0x1d, 0x64, 0x0f, 0x40, 0x48, 0x55, 0xd2, 0xc2, 0xd6,
	0x13, 0x6d, 0x59, 0xad, 0xd7, 0xda, 0xb0, 0xb2, 0xe4, 0xb4, 0x88, 0xbc, 0xe4, 0x63, 0xfb, 0xda,
	0x76, 0x5f, 0xbf, 0xa3, 0xe1, 0x49, 0x08, 0xc3, 0xa5, 0x94, 0xb9, 0x8e, 0xfc, 0x1f, 0x46, 0xf8,
	0xf7, 0xe7, 0xd3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x54, 0xe8, 0x92, 0x7b, 0x0c, 0x09, 0x00,
	0x00,
}
