// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / 下发用户数据错误枚举
type S2C_UserData_E_Error int32

const (
	S2C_UserData_Error_ S2C_UserData_E_Error = 0
	// / OK
	S2C_UserData_OK S2C_UserData_E_Error = 1
	// / 没有用户数据
	S2C_UserData_NotExist S2C_UserData_E_Error = 2
)

var S2C_UserData_E_Error_name = map[int32]string{
	0: "Error_",
	1: "OK",
	2: "NotExist",
}
var S2C_UserData_E_Error_value = map[string]int32{
	"Error_":   0,
	"OK":       1,
	"NotExist": 2,
}

func (x S2C_UserData_E_Error) String() string {
	return proto.EnumName(S2C_UserData_E_Error_name, int32(x))
}
func (S2C_UserData_E_Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_8bdc377fcc426676, []int{1, 0}
}

// / 用户数据
type User struct {
	// / id
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// / 名字
	NickName string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	// / 性别
	Sex int32 `protobuf:"varint,3,opt,name=Sex,proto3" json:"Sex,omitempty"`
	// / 物品
	Items []*Item `protobuf:"bytes,4,rep,name=Items,proto3" json:"Items,omitempty"`
	// / 货币
	Monies []*Money `protobuf:"bytes,6,rep,name=Monies,proto3" json:"Monies,omitempty"`
	// /等级
	Level int32 `protobuf:"varint,21,opt,name=Level,proto3" json:"Level,omitempty"`
	// /经验
	Exp                  int64    `protobuf:"varint,22,opt,name=Exp,proto3" json:"Exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8bdc377fcc426676, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *User) GetMonies() []*Money {
	if m != nil {
		return m.Monies
	}
	return nil
}

func (m *User) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *User) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

// / 服务端下发用户信息
// @msg
type S2C_UserData struct {
	// / 错误枚举
	Err S2C_UserData_E_Error `protobuf:"varint,1,opt,name=Err,proto3,enum=msg.S2C_UserData_E_Error" json:"Err,omitempty"`
	// / 用户数据
	Data                 *User    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_UserData) Reset()         { *m = S2C_UserData{} }
func (m *S2C_UserData) String() string { return proto.CompactTextString(m) }
func (*S2C_UserData) ProtoMessage()    {}
func (*S2C_UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8bdc377fcc426676, []int{1}
}
func (m *S2C_UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_UserData.Unmarshal(m, b)
}
func (m *S2C_UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_UserData.Marshal(b, m, deterministic)
}
func (dst *S2C_UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_UserData.Merge(dst, src)
}
func (m *S2C_UserData) XXX_Size() int {
	return xxx_messageInfo_S2C_UserData.Size(m)
}
func (m *S2C_UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_UserData proto.InternalMessageInfo

func (m *S2C_UserData) GetErr() S2C_UserData_E_Error {
	if m != nil {
		return m.Err
	}
	return S2C_UserData_Error_
}

func (m *S2C_UserData) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

// / 更新用户信息请求
// @msg
type C2S_UpdateUserData struct {
	// / 用户id
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_UpdateUserData) Reset()         { *m = C2S_UpdateUserData{} }
func (m *C2S_UpdateUserData) String() string { return proto.CompactTextString(m) }
func (*C2S_UpdateUserData) ProtoMessage()    {}
func (*C2S_UpdateUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8bdc377fcc426676, []int{2}
}
func (m *C2S_UpdateUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_UpdateUserData.Unmarshal(m, b)
}
func (m *C2S_UpdateUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_UpdateUserData.Marshal(b, m, deterministic)
}
func (dst *C2S_UpdateUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_UpdateUserData.Merge(dst, src)
}
func (m *C2S_UpdateUserData) XXX_Size() int {
	return xxx_messageInfo_C2S_UpdateUserData.Size(m)
}
func (m *C2S_UpdateUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_UpdateUserData.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_UpdateUserData proto.InternalMessageInfo

func (m *C2S_UpdateUserData) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "msg.User")
	proto.RegisterType((*S2C_UserData)(nil), "msg.S2C_UserData")
	proto.RegisterType((*C2S_UpdateUserData)(nil), "msg.C2S_UpdateUserData")
	proto.RegisterEnum("msg.S2C_UserData_E_Error", S2C_UserData_E_Error_name, S2C_UserData_E_Error_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_8bdc377fcc426676) }

var fileDescriptor_user_8bdc377fcc426676 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xff, 0x69, 0xb6, 0xfe, 0xb7, 0xb3, 0x31, 0xca, 0x41, 0x25, 0x0e, 0xc4, 0x52, 0xbc,
	0x28, 0x0c, 0x7a, 0x51, 0x1f, 0x61, 0xeb, 0xc5, 0xd0, 0x4d, 0x48, 0xd9, 0x75, 0xa9, 0x1a, 0x46,
	0xd1, 0x2c, 0x25, 0x89, 0x52, 0x9f, 0xc0, 0xe7, 0xf1, 0x0d, 0x25, 0xe9, 0x9c, 0xde, 0x9d, 0xef,
	0x3b, 0x1f, 0x27, 0xbf, 0x7c, 0x00, 0x6f, 0x46, 0xe8, 0xac, 0xd5, 0xca, 0x2a, 0xa4, 0xd2, 0xec,
	0xe7, 0xd0, 0x58, 0x21, 0x7b, 0x63, 0x3e, 0x91, 0xea, 0x20, 0x3e, 0x7a, 0x91, 0x7c, 0x11, 0x18,
	0xec, 0x8c, 0xd0, 0x38, 0x83, 0x60, 0xbd, 0x62, 0x24, 0x26, 0x29, 0xe5, 0xc1, 0x7a, 0x85, 0x73,
	0x18, 0x6d, 0x9b, 0xa7, 0x97, 0x6d, 0x2d, 0x05, 0x0b, 0x62, 0x92, 0x8e, 0xf9, 0x49, 0x63, 0x04,
	0xb4, 0x14, 0x1d, 0xa3, 0x31, 0x49, 0x87, 0xdc, 0x8d, 0x78, 0x0d, 0xc3, 0xb5, 0x15, 0xd2, 0xb0,
	0x41, 0x4c, 0xd3, 0x49, 0x3e, 0xce, 0xa4, 0xd9, 0x67, 0xce, 0xe1, 0xbd, 0x8f, 0x09, 0x84, 0x1b,
	0x75, 0x68, 0x84, 0x61, 0xa1, 0x4f, 0x80, 0x4f, 0x6c, 0x1c, 0x09, 0x3f, 0x6e, 0xf0, 0x0c, 0x86,
	0xf7, 0xe2, 0x5d, 0xbc, 0xb2, 0x73, 0x7f, 0xb8, 0x17, 0xee, 0xb1, 0xa2, 0x6b, 0xd9, 0x85, 0x27,
	0x73, 0x63, 0xf2, 0x49, 0x60, 0x5a, 0xe6, 0xcb, 0xca, 0x71, 0xaf, 0x6a, 0x5b, 0xe3, 0x02, 0x68,
	0xa1, 0xb5, 0x87, 0x9f, 0xe5, 0x97, 0xfe, 0xf2, 0xdf, 0x7d, 0x56, 0x54, 0x85, 0xd6, 0x4a, 0x73,
	0x97, 0xc2, 0x2b, 0x18, 0x38, 0xd3, 0x7f, 0xea, 0x87, 0xd4, 0x25, 0xb9, 0xb7, 0x93, 0x05, 0xfc,
	0x3f, 0xc6, 0x11, 0x20, 0xf4, 0x43, 0x15, 0xfd, 0xc3, 0x10, 0x82, 0x87, 0xbb, 0x88, 0xe0, 0x14,
	0x46, 0x5b, 0x65, 0x8b, 0xae, 0x31, 0x36, 0x0a, 0x92, 0x1b, 0xc0, 0x65, 0x5e, 0x56, 0xbb, 0xf6,
	0xb9, 0xb6, 0xe2, 0x84, 0xf3, 0x5b, 0xe5, 0xd8, 0x55, 0xf9, 0x18, 0xfa, 0xaa, 0x6f, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x1a, 0x5f, 0xc2, 0x62, 0x96, 0x01, 0x00, 0x00,
}
