// Code generated by protoc-gen-enum-go. DO NOT EDIT IT!!!
// source: user.proto

/*
It has these top-level messages:
	User
*/

package model

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// enum [E_UserSex] begin

type E_UserSex int32

const (
	UserSex_ E_UserSex = 0
	/// 男性
	Male E_UserSex = 1
	/// 女性
	Female E_UserSex = 2
)

var E_UserSex_name = map[int32]string{
	0: "UserSex_",
	1: "Male",
	2: "Female",
}

var E_UserSex_value = map[string]int32{
	"UserSex_": 0,
	"Male":     1,
	"Female":   2,
}

var E_UserSex_Slice = []int32{
	0,
	1,
	2,
}

func (x E_UserSex) String() string {
	if name, ok := E_UserSex_name[int32(x)]; ok {
		return name
	}
	return ""
}

func E_UserSex_Len() int {
	return len(E_UserSex_Slice)
}

func Check_E_UserSex_I(value int32) bool {
	if _, ok := E_UserSex_name[value]; ok && value != 0 {
		return true
	}
	return false
}

func Check_E_UserSex(value E_UserSex) bool {
	return Check_E_UserSex_I(int32(value))
}

func Each_E_UserSex(f func(E_UserSex) bool) {
	for _, value := range E_UserSex_Slice {
		if !f(E_UserSex(value)) {
			break
		}
	}
}

func Each_E_UserSex_I(f func(int32) bool) {
	for _, value := range E_UserSex_Slice {
		if !f(value) {
			break
		}
	}
}

// enum [E_UserSex] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
